//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vers0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contractor()
        {
            this.orders = new HashSet<orders>();
        }
    
        public string INN { get; set; }
        public string type_contractor { get; set; }
        public string address_contractor { get; set; }
        public string RCBIC { get; set; }
        public string bank { get; set; }
        public string corr_acc { get; set; }
        public string acc { get; set; }
        public string designation_contractor { get; set; }
        public string KPP { get; set; }
        public string OGRN { get; set; }
        public string surname { get; set; }
        public string name_contractor { get; set; }
        public string middle_name { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public string OGRNIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
