//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vers0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int number { get; set; }
        public string username { get; set; }
        public System.DateTime date_action { get; set; }
        public int type_action { get; set; }
    
        public virtual user_action user_action { get; set; }
        public virtual users users { get; set; }
    }
}
