//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vers0.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;
    using System.Linq;

    public partial class inventory_managementEntities : DbContext
    {
        public inventory_managementEntities()
            : base("name=inventory_managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contractor> contractor { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<products_in_order> products_in_order { get; set; }
        public virtual DbSet<user_action> user_action { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual bool UserAuthorization(string username, string password)
        {
            var result = Database.SqlQuery<bool>("SELECT dbo.user_authorization(@username, @password)",
                new SqlParameter("username", username),
                new SqlParameter("password", password)
            ).Single();

            return result;
        }
    }
}
