//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vers0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_in_order
    {
        public int number { get; set; }
        public int order_number { get; set; }
        public int product_number { get; set; }
        public int quantity { get; set; }
        public double price { get; set; }
        public double amount { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual product product { get; set; }
    }
}
